sudo: required
dist: trusty
language: node_js
cache:
  - npm
  - directories:
      - "$HOME/.cache/electron"
      - "$HOME/.cache/electron-builder"
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: Tm4Hp9fO/MB/b0t/r14XU2AYLPYFV7m0XzI4f0F652wiJ+ThWC/+cWlLsUYrXVNLvWe6Ry+ifZFV4u2tkbK07EN5HvmN27/BHg2PA7cnewrBN+BqJBAjK/U+yKN3L4Gl9N2xKKkBEUwxaeoxcCmiRlIRLnSWdFk3rSZyC3YDCAsduVZ7QX1dkiyX3no5aIZ7BN7G7zJyIIciwH+i9f6wET+7p5pO+Ypeb9avXVTA0oB7DhSXv+PcS/GljVNdSLolsxj44XtWut40Q4QnHamHwT2MgCewXnWD4k3x76UMy1axlyWmN8ezvXV7917gz+ufQ50ahV/92Mi5EoY2mfw1rFK+cAYPcoGNZbou8fVOhcfHcjDT2Xq8Ua9t9M6IPhCNCprSPybsy2riIEL1XAQD1auKs5CHuTTiB7jc7nkdsAUkH6kJbcmSEuudgdbq7oeKThL86oTW2GMfgJCx18KwJFuVWyHz1a0QusDSUYGQGIFgPNPe6ei4R0OzoH2W3MWrJG3U91bsraXCVI2NEWgf/u1UITrsS/vtFleAhCSOjnVtGOyoAs+FpLBKXnDnEZmQ3WTph6faEMgANInYcxPkLDf/lK2cjy4qNZjBiG+72FKSfDT6JBSurEv5QJyj13o1MNvlWqonoF9wLpGCAhCzVkn1KobFvhaMCGYLoL7JrDc=
matrix:
  fast_finish: true
  include:
    - os: linux
      # node_js: lts/*
      # node_js: 12.4.0
      node_js: node
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      compiler: clang
    - os: osx
      osx_image: xcode10.2
      # node_js: lts/*
      # node_js: 12.4.0
      node_js: node
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      # - snapd
before_install:
  - openssl aes-256-cbc -K $encrypted_56d791a64072_key -iv $encrypted_56d791a64072_iv
    -in ./dev-assets/travis-secrets.tar.enc -out ./dev-assets/travis-secrets.tar -d
  - tar xvf ./dev-assets/travis-secrets.tar -C ./dev-assets
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then base64 -i ./dev-assets/code-sign-certificate-quark.p12
    -o ./dev-assets/envValue.txt; fi
  - "if [ $TRAVIS_BRANCH == \"master\" ] || [ $TRAVIS_BRANCH == \"master-all\" ]; then\n
    \   export QUARK_RUN_BUILD=true;\n  else \n    export QUARK_RUN_BUILD=false;\nfi\n"
  # - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then sudo
  #   snap install snapcraft --classic; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then export
    DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
  - echo $QUARK_RUN_BUILD
  - npm install
before_script:
  - node --version
  - npm --version
script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then xattr -cr *; fi
  - npm run build-ci
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run test-ci; fi

after_success:
  - npm run upload-ci
  - ls -la ./build
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls -la ./build/mac; fi
