name: Build and release
on:
  push:
    branches:
      - master
      - master-all

jobs:
  build:
    name: Build ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip github]')"
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Decrypt secret file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output ./dev-assets/github-actions.secrets.tar ./dev-assets/github-actions.secrets.tar.gpg
        shell: bash
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Extract tar archive
        shell: bash
        run: tar xvf ./dev-assets/github-actions.secrets.tar -C ./dev-assets
      - name: Install dependencies
        run: npm install
      - name: Build binaries
        run: npm run build-ci
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        if: runner.os != 'macOS'
        with:
          run: npm run test-ci
      - name: Upload binaries
        run: npm run upload-ci
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   if: runner.os == 'macOS'
      #   with:
      #     name: build
      #     path: ./build
      # - name: Send slack notification
      #   uses: rtCamp/action-slack-notify@v2.0.0
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
