name: Greet Everyone
on:
  push:
    branches:
      - master
      - master-all

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Decrypt secret file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output ./dev-assets/github-actions.secrets.tar ./dev-assets/github-actions.secrets.tar.gpg
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Extract tar archive
        run: tar xvf github-actions.secrets.tar -C ./dev-assets
      - name: Install dependencies
        run: npm install
      - name: Build binaries
        run: npm run build-ci